language: node_js
node_js:
- 0.1
env:
  global:
  - secure: O9NvY6v3q9vG0KBOytt2qW6i6YRNpybCxjEXyc8kXJ7siyN6yquRj06DHZOhpfnf9zZXrM/QDmk4Deu1Lpgtx6nUBO4+LKVvPAC8hfQSl87bt6TeKMR4pr5+wEjK2ngijdMXyBr+8hu+Ke9FL4ZjyhDpv4lPUldCpg1OB2ttdag=
  - secure: D1+0u8YZzt7qkI63eUG01Crj+havgKreig6vbW0qO7rJoB80pNFQP5SFu48lofNz5IUXM45n+/zMuU2J9y1dzAn2keDlbiJW9gnX25zrZYTVyyqmjwxOfCLGXD69geXcohMHtxDLAi5Scou3zGEfW7wcdsT1O44UDaC2WzRW63U=

before_script:
- npm install component component-stylus git+https://github.com/mvanasse/saucer
- component install
- component build --standalone shoelace-modal --use component-stylus
script: saucer test
