language: node_js
node_js:
  - 0.10

env:
  global:
  - secure: OJsg/8b0wVuhZKTSF2OjBCgw+Y7UgcgtaS1eh0QGCCt80ttXZFoaKK+ZlviNBi39blXY25QGGQZtZTIfvuxFXeSEpDIPmNlaIsEjDrdHxyU8MbNTLxQyj8/gqQCI6pJ36SJqn7MlNVT4r8IEGVQHvnBcZWKwct5d7F6tpDBBOos=
  - secure: mVdimSbzg72XZhssLaGRS/L3X27VF0CzB4EkAEEs5xBP3o7GNH5pEMmyLKlYYvigqctbfX5kJWxbTMqkbHeinU1I9sXwPKrSyXjTG6HLZdj1Nb8q/RH/u2haKLDqsbxtuYxcn5EyhFMxxTK/iX4yw04QYjYzkNptdLG13/WLobw=

before_script:
  - npm install component component-stylus git+https://github.com/mvanasse/saucer
  - component install
  - component build --standalone shoelace-modal --use component-stylus

script: saucer test
